import {
    LayoutDashboard,
    ShoppingCart,
    Package,
    Tags,
    Warehouse,
    Users,
    Clock,
    Receipt,
    Printer,
    BarChart3,
    History,
    UserCog,
    Settings,
} from "lucide-react";

export const NAV_BY_ROLE = {
    ADMIN: [
        { label: "Dashboard", to: "/admin/dashboard", icon: LayoutDashboard },
        { label: "Bán hàng", to: "/admin/pos", icon: ShoppingCart },
        { label: "Sản phẩm", to: "/admin/products", icon: Package },
        { label: "Danh mục", to: "/admin/categories", icon: Tags },
        { label: "Kho hàng", to: "/admin/inventory", icon: Warehouse },
        { label: "Nhân viên", to: "/admin/employees", icon: Users },
        { label: "Ca làm việc", to: "/admin/shifts", icon: Clock },
        { label: "Hóa đơn", to: "/admin/invoices", icon: Receipt },
        { label: "Đơn in", to: "/admin/print-orders", icon: Printer },
        { label: "Báo cáo", to: "/admin/reports", icon: BarChart3 },
        { label: "Lịch sử", to: "/admin/activity-logs", icon: History },
        { label: "Tài khoản", to: "/admin/users", icon: UserCog },
        { label: "Cài đặt", to: "/admin/settings", icon: Settings },
    ],
    MANAGER: [
        { label: "Dashboard", to: "/manager/dashboard", icon: LayoutDashboard },
        { label: "Bán hàng", to: "/manager/pos", icon: ShoppingCart },
        { label: "Sản phẩm", to: "/manager/products", icon: Package },
        { label: "Kho", to: "/manager/inventory", icon: Warehouse },
        { label: "Nhân viên", to: "/manager/employees", icon: Users },
        { label: "Ca làm", to: "/manager/shifts", icon: Clock },
        { label: "Hóa đơn", to: "/manager/invoices", icon: Receipt },
        { label: "Đơn in", to: "/manager/print-orders", icon: Printer },
        { label: "Báo cáo", to: "/manager/reports", icon: BarChart3 },
    ],
    STAFF: [
        { label: "Bán hàng", to: "/staff/pos", icon: ShoppingCart },
        { label: "Sản phẩm", to: "/staff/products", icon: Package },
        { label: "Hóa đơn", to: "/staff/invoices", icon: Receipt },
        { label: "Đơn in", to: "/staff/print-orders", icon: Printer },
        { label: "Ca làm", to: "/staff/shift", icon: Clock },
    ],
};